version: '3.7'
services:

    flask:
        build: ./flask
        command: gunicorn -c "python:config.gunicorn" --reload "quickslack.app:create_app()"
        container_name: flask
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - './flask:/flask'

    redis:
        image: redis:3.0-alpine
        container_name: redis
        command: redis-server --requirepass devpassword
        restart: unless-stopped
        volumes:
            - 'redis:/var/lib/redis/data'

    # beat:
    #     build: ./flask
    #     container_name: beat
    #     command: celery worker -B -l info -A quickslack.CELERY
    #     restart: unless-stopped
    #     env_file:
    #         - ./.env
    #     volumes:
    #         - './flask:/flask'

    task-monitor:
        build: ./flask
        container_name: task-monitor
        entrypoint: flower
        command: -A quickslack.CELERY
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - './flask:/flask'

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - postgres:/var/lib/postgresql/data

    api:
        container_name: model
        restart: unless-stopped
        build: './model'
        command: gunicorn -c "python:config.gunicorn" --reload "api.app:create_app()"
        volumes:
            - './model:/api'

volumes:
    postgres:
    redis: