version: '3.7'
services:
    flask:
        ports:
            - 8000:8000
    redis:
        ports:
            - 6379:6379
    postgres:
        ports:
            - 5432:5432
    task-monitor:
        ports:
            - 5555:5555
    api:
        ports:
            - 8080:8080
