version: '3.7'
services:
  flask:
    env_file:
      - ./.env
    ports:
      - 8000:8000
  redis:
    ports:
      - 5432:5432
  postgres:
    env_file:
      - ./.env
    ports:
      - 5432:5432
  task-monitor:
    ports:
      - 5555:5555
