version: '3.7'
services:
    flask:
        build: ./flask
        command: gunicorn -c "python:config.gunicorn" --reload "quickslack.app:create_app()"
        container_name: flask
        restart: unless-stopped
        volumes:
            - './flask:/flask'
    redis:
        image: redis:3.0-alpine
        container_name: redis
        command: redis-server --requirepass devpassword
        restart: unless-stopped
        volumes:
            - 'redis:/var/lib/redis/data'
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: unless-stopped
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:
    redis: