
version: '3.7'
services:

    flask:
        build: ./flask
        command: gunicorn -c "python:config.gunicorn" --reload "quickslack.app:create_app()"
        container_name: flask
        restart: unless-stopped
        env_file:
            - ./.env.example
        ports:
            - '8000:8000'
        volumes:
            - './flask:/flask'

    redis:
        image: redis:3.0-alpine
        container_name: redis
        command: redis-server --requirepass devpassword
        restart: unless-stopped
        volumes:
            - 'redis:/var/lib/redis/data'
        ports:
            - '6379:6379'

    celery:
        build: ./flask
        container_name: celery
        command: celery worker -B -l info -A quickslack.CELERY
        restart: unless-stopped
        env_file:
            - ./.env.example
        volumes:
            - './flask:/flask'

    task-monitor:
        build: ./flask
        container_name: task-monitor
        entrypoint: flower
        command: -A quickslack.CELERY
        restart: unless-stopped
        env_file:
            - ./.env.example
        volumes:
            - './flask:/flask'
        ports:
            - "5555:5555"

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: unless-stopped
        env_file:
            - ./.env.example
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres:
    redis: